### ISSUE TITLE
Initialize as a constructor

### ISSUE THREAD

**Issue by yoshuawuyts** [YerkoPalma/choo-tts#5]
Was thinking it might make sense to make this module be a constructor. I'd imagine there could be a thing where we can for example include a list of voices, that are checked for availability, and the first one in the list is picked. Just like with fonts. But it'd require the API to change, and include a constructor. Thoughts?

```js
var voices = [ 'kyla', 'james', 'junior' ]
app.use(require('choo-tts')({ voice: voices })
```

**Comment by YerkoPalma** [comment]
I don't think a constructor is the best fit because we are adding events and properties, not creating new objects. But wrapping in a function that returns a choo store makes a lot of sense to me. Something like

```js
function tts (opts) {
  return function (state, emitter) {
  }
}
```

This pattern is common in other choo stores, so it sounds logical to me. I'm curious tho, what options would you add?
